[package]
name = "dir2"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
open = "5.3.2"
rust_search = "2.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
